version: "3" 
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    command: ls -l /codefresh/volume/home
    volumes:
      - type: bind
        source: /var/lib/docker/volumes/${CF_VOLUME_NAME}/_data/${CF_REPO_NAME}/vol/ssl
        target: /codefresh/volume/ssl
      #- "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
