version: "3" 
services:
  web:
    image: nginx:latest
    name: server1
    ports:
      - "8080:80"
    command: ls -l /codefresh/volume/ssl
    volumes:
      - type: bind
        source: ${CF_VOLUME_REPO_PATH}/vol/ssl
        target: /codefresh/volume/ssl
      #- "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
