version: "3" 
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: ./ssl
        destination: /home/ssl
      #- "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
